server:
  port: 8080
courier:
  provider:
    serverAddress: 127.0.0.1:20880
    registryAddress: 192.168.3.37:2181
    registerType: ZOOKEEPER
    reflectType: ASM
    heartbeatInterval: 10
    heartbeatIntervalTimeUnit: SECONDS
    scanNotActiveChannelInterval: 30
    scanNotActiveChannelIntervalTimeUnit: SECONDS

