server:
  port: 8080
courier:
  provider:
    serverAddress: 192.168.3.122:20880
    registryAddress: 192.168.3.37:2181
    registerType: ZOOKEEPER
    reflectType: JDK
    heartbeatInterval: 10
    heartbeatIntervalTimeUnit: SECONDS
    scanNotActiveChannelInterval: 30
    scanNotActiveChannelIntervalTimeUnit: SECONDS

